<?php
declare(strict_types=1);
/**
 *   _   _  _____ ______                    _   _       _
 *  | \ | |/ ____|  ____|                  | | (_)     | |
 *  |  \| | |  __| |__   ___ ___  ___ _ __ | |_ _  __ _| |___
 *  | . ` | | |_ |  __| / __/ __|/ _ \ '_ \| __| |/ _` | / __|
 *  | |\  | |__| | |____\__ \__ \  __/ | | | |_| | (_| | \__ \
 *  |_| \_|\_____|______|___/___/\___|_| |_|\__|_|\__,_|_|___/
 *
 * Copyright (C) 2016-2020 NetherGames Network
 *
 * This is private software, you cannot redistribute and/or modify it in any way
 * unless given explicit permission to do so. If you have not been given explicit
 * permission to view or modify this software you should take the appropriate actions
 * to remove this software from your device immediately.
 *
 * @author k3ithos, matcracker, driesboy
 *
 */

namespace NetherGames\NGEssentials\lang\locale;


class English implements Language
{

    public function translations(): array
    {
        return [
            LangConstants::COMMAND_RESERVED_STAFF => '&cThat command is available only for &eNether&6Games &cstaff',
            LangConstants::COMMAND_RESERVED_ESTAFF => '&cThat command is available only for &eNether&6Games &cexecutive staff',
            LangConstants::COMMAND_PING => '&6Your ping to the server (&b%0&6) is currently %1ms',
            LangConstants::COMMAND_RECONNECT_BW => '&cThe last server you were detected to be playing on is not a BW server',
            LangConstants::COMMAND_RECONNECT_NOT_FOUND => '&cThe last server you were detected to be playing on is not available',
            LangConstants::COMMAND_STATS_PLAYER_INFO => '&6Player Info (&b%0&6)',
            LangConstants::COMMAND_STATS_ONLINE => '&aStatus: &2ONLINE',
            LangConstants::COMMAND_STATS_OFFLINE => '&aStatus: &cOFFLINE',
            LangConstants::COMMAND_STATS_CURRENTLY => '&aCurrently on: &f%0',
            LangConstants::COMMAND_STATS_LAST => '&aLast seen on: &f%0',
            LangConstants::COMMAND_STATS_KILLS => '&aKills: &f%0',
            LangConstants::COMMAND_STATS_DEATHS => '&aDeaths: &f%0',
            LangConstants::COMMAND_STATS_CREDITS => '&aCredits: &f%0',
            LangConstants::COMMAND_STATS_LEVEL => '&aLevel: &f%0',
            LangConstants::COMMAND_STATS_XP => '&aXP: &f%0',
            LangConstants::COMMAND_CI_COMPLETED => '&aYour inventory has been cleared',
            LangConstants::COMMAND_CI_NO_PERM => "&cYou don't have permission to clear your inventory! You can buy the &l&bLEGEND&r &crank at &bngmc.co/store &cto unlock this feature!",
            LangConstants::COMMAND_MEGA_CREATIVE_NO_PERM => '&cMega Creative is only for players who have voted at &6ngmc.co/v§',
            LangConstants::COMMAND_NOT_IN_LOBBY => '&cThat command can be permormed only in lobby',
            LangConstants::COMMAND_REPLY_NO_PERM => "&cYou don't have permission to use the quick reply feature. You can buy the &l&bLEGEND&r &c rank at &bngmc.co/store &cto unlock this feature!",
            LangConstants::COMMAND_TELL_BLOCK => '&b%0 &chas blocked all direct messages',
            LangConstants::COMMAND_TELL_DENY => '&b%0 &cdoes not accept direct messages from you',
            LangConstants::COMMAND_TELL_RECEIVER => '&b%0 %6whispered to you: &c',
            LangConstants::COMMAND_TELL_SENDER => '&6You whispered to &b%0&6: &c%1',
            LangConstants::COMMAND_TELL_YOURSELF => '&cWhy should you whisper to yourself, hm?',
            LangConstants::COMMAND_TELL_MUTED => '&cYou are temporarily muted for &b%0 &7(&e#%1&7)\n&cYour mute will expire in &b%2\n&7If you believe your mute is unjustified, you may appeal it at &engmc.co/um',
            LangConstants::COMMAND_TELL_MUTED_PERMA => '&cYou are permanently muted for &b%0 &7(&e#%1&7)\n&7If you believe your mute is unjustified, you may appeal it at &engmc.co/um',
            LangConstants::COMMAND_TELL_QUICK => '&Calm down, don\'t chat too quickly!',
            LangConstants::COMMAND_TELL_ADVERTISE => '&Advertising is not allowed!',
            LangConstants::COMMAND_TELL_OFFLINE => '&6That player is currently not online, but they will receive your message the next time they join the server.',
            LangConstants::COMMAND_VOTE_SLOWDOWN => "&cWow wow, slow down, we're checking votes for you already!",
            LangConstants::COMMAND_SOCIAL_NOT_SUPPORTED => '&cThis server does not support social features',

            LangConstants::DOUBLE_XP => 'Double XP weekend',

            LangConstants::PROFANITY_QUICK => '&cCalm down, don\'t chat too quickly',
            LangConstants::PROFANITY_ADVERTISE => '&cAdvertising is not allowed',

            LangConstants::ITEM_REPORTER => '&r&c&lReport Player',
            LangConstants::ITEM_REPORTER_LORE => '&r&bRight-click to report a player',
            LangConstants::ITEM_UTILITY => '&r&b&lUtilities',
            LangConstants::ITEM_UTILITY_LORE => '&r&bRight-click to open the cosmetic menu',
            LangConstants::ITEM_SOCIAL => '&r&d&lSocial Menu',
            LangConstants::ITEM_SOCIAL_LORE => '&r&bRight-click to manage your party',
            LangConstants::ITEM_TELEPORTER => '&r&a&lTeleporter',
            LangConstants::ITEM_TELEPORTER_LORE => '&r&bRight-click to teleport to a minigame',
            LangConstants::ITEM_PROFILE => '&r&e&lProfile Settings',
            LangConstants::ITEM_PROFILE_LORE => '&r&bRight-click to change your profile settings',
            LangConstants::ITEM_REPLAY_RESUME => '&r&b&lResume the replay',
            LangConstants::ITEM_REPLAY_RESUME_LORE => '&r&7Right-click to resume the replay',
            LangConstants::ITEM_REPLAY_PAUSE => '&r&b&lPause the replay',
            LangConstants::ITEM_REPLAY_PAUSE_LORE => '&r&7Right-click to pause the replay',
            LangConstants::ITEM_NOCLIP => '&r&e&lToggle No Clip',
            LangConstants::ITEM_NOCLIP_LORE => '&r&7Right-click to toggle no clip',
            LangConstants::ITEM_SPECTATE => '&r&a&lTeleporter',
            LangConstants::ITEM_SPECTATE_LORE => '&r&7Right-click to spectate',
            LangConstants::ITEM_PARKOUR_BED => '&r&c&lQuit the parkour &7(Right-Click)',
            LangConstants::ITEM_PARKOUR_BED_LORE => '&r§7Right-click to leave the parkour',
            LangConstants::ITEM_PARKOUR_DOOR => '&r&c&lReset &7(Right-Click)',
            LangConstants::ITEM_PARKOUR_DOOR_LORE => '&r&7Right-click to reset the parkour',
            LangConstants::ITEM_PARKOUR_SLAB => '&r&a&lTeleport to Last Checkpoint &7(Right-Click)',
            LangConstants::ITEM_PARKOUR_SLAB_LORE => '&r&7Right-click to teleport to your last checkpoint',
            LangConstants::ITEM_LOBBY => '&r&c&lReturn to Lobby',
            LangConstants::ITEM_LOBBY_LORE => '&r&7Right-click to return to the lobby',

            LangConstants::COSMETICS_IN_USE => '&cI\'m currently in use. Try again later',
            LangConstants::COSMETICS_NOT_ENOUGH_KEYS => '&cYou don\'t have enough keys!',
            LangConstants::COSMETICS_ALL => '&cYou\'ve already claimed all cosmetics!',

            LangConstants::DATABASE_ERROR => '&l&cAn unexpected error occurred while connecting to database. Please, try again later',
            LangConstants::SOMETHING_WRONG => '&cSomething went wrong, please try again later!',
            LangConstants::MESSAGE_REPORT => '&cIs this message abusive or inappropriate? &6Take a screenshot and report it - &angmc.co/r  &6or &a#report channel on our Discord (ngmc.co/d)',

            LangConstants::FORMS_BUTTON_BACK => '&cBack',
            LangConstants::FORMS_BUTTON_FULL => '&cFULL',
            LangConstants::FORMS_BUTTON_YES_GREEN => '&aYes',
            LangConstants::FORMS_BUTTON_YES_RED => '&cYes',
            LangConstants::FORMS_BUTTON_NO_GREEN => '&aNo',
            LangConstants::FORMS_BUTTON_NO_RED => '&cNo',

            LangConstants::FORMS_CHAT_TYPE => 'Chat Type',
            LangConstants::FORMS_HANDLER_CHAT_TYPE => '&aEnabled &b%0 &achat',
            LangConstants::FORMS_CHAT_COLOR => 'Chat Color',
            LangConstants::FORMS_HANDLER_CHAT_COLOR => '&aYou have selected %0 as your chat color',

            LangConstants::FORMS_PROFILE_RULES_1 => '§aWelcome to §eNether§6Games§a.',
            LangConstants::FORMS_PROFILE_RULES_2 => '§eNether§6Games §bis a community-based server network with a wide variety of games to entertain Minecraft players of all ages.',
            LangConstants::FORMS_PROFILE_RULES_3 => '§bBefore you start your journey here, we\'d like you to read through the following guidelines and expectations we have of you while using our services. These rules help us ensure that all players are able to enjoy a positive and fun experience.',
            LangConstants::FORMS_PROFILE_RULES_4 => '§e1. Respect yourself and others',
            LangConstants::FORMS_PROFILE_RULES_4_DESCRIPTION => '§7Do not swear, curse, or hurl abuse at another player. Respect other players and treat others as you would like to be treated. Bullying in any form is not tolerated at NetherGames and offenders will be prosecuted accordingly.',
            LangConstants::FORMS_PROFILE_RULES_5 => '§e2. Keep your content appropriate',
            LangConstants::FORMS_PROFILE_RULES_5_DESCRIPTION => '§7Do not post inappropriate content. A good way to check if your content is appropriate is to ask yourself - is this something that I could show to my parents? This definition also includes material that others could potentially find offensive. Racism, sexism or any other form of discrimination is strictly prohibited.',
            LangConstants::FORMS_PROFILE_RULES_6 => '§e3. Be considerate while chatting',
            LangConstants::FORMS_PROFILE_RULES_6_DESCRIPTION => '§7Think about others and what they will see in the chat when you post a message. Do not spam, repeatedly use the same word/phrase, or use excessive caps in your messages to attract attention or to annoy others. Respect the fact that there is a chat filter in place for a reason. Swearing is allowed to a certain degree, as long as it is appropriately censored and is not directed to another player.',
            LangConstants::FORMS_PROFILE_RULES_7 => '§e4. Listen to and respect our staff members',
            LangConstants::FORMS_PROFILE_RULES_7_DESCRIPTION => "§7Our staff members are here to ensure that everyone is having a great time. When they give you an instruction, we expect that you follow what they say.\nKeep in mind that our staff team is comprised of volunteers. They are here to help and to keep the server safe - but they are not your personal servants. When asking questions or engaging in conversation with them, do so in a polite manner.",
            LangConstants::FORMS_PROFILE_RULES_8 => '§e5. Advertising/endorsing other servers is not allowed',
            LangConstants::FORMS_PROFILE_RULES_8_DESCRIPTION => '§7Advertising or endorsing another Minecraft Bedrock Edition server is strictly prohibited at NetherGames. Other servers may be mentioned if they are to be used to provide context in a conversation, however any other form of conversation relating to another server will be treated as advertising.',
            LangConstants::FORMS_PROFILE_RULES_9 => '§e6. Keep your personal information safe',
            LangConstants::FORMS_PROFILE_RULES_9_DESCRIPTION => '§7While we would love to believe that there are no bad people in the world, this is simply not realistic. Keep your personal information to yourself - this is the internet. Keep in mind that all conversations and messages you send are posted on a public forum, which is likely where they will stay forever.',
            LangConstants::FORMS_PROFILE_RULES_10 => '§e7. Turn off your client modifications',
            LangConstants::FORMS_PROFILE_RULES_10_DESCRIPTION => '§7Using client modifications or "cracked clients" that are not officially endorsed by Minecraft are not allowed to be used on NetherGames. Prohibited modifications include ones that give you abilities that are not obtained rightfully - e.g. fly hacking, jump/speed boost, auto clicking, etc. Resource/texture packs that provide cosmetic changes which do not affect gameplay and/or provide advantages are allowed.',
            LangConstants::FORMS_PROFILE_RULES_11 => '§e8. Use an appropriate username and skin',
            LangConstants::FORMS_PROFILE_RULES_11_DESCRIPTION => '§7Keep your username and skin appropriate for players of all ages. Prohibited skins include ones that may provide an advantage, such as one that uses custom geometry and not the "Alex" or "Steve" skin structure, or ones that show an excessive amount of body parts.',
            LangConstants::FORMS_PROFILE_RULES_12 => '§e9. Be thoughtful of your teammates and other players',
            LangConstants::FORMS_PROFILE_RULES_12_DESCRIPTION => "§7When playing in a match where you are placed in a team with other players, keep them in mind. Trying to troll, grief or kill them is not acceptable.\nIf you are in a solo match against other players, teaming with other players is not allowed. There is a reason why solo and team matches are separated.\nOn Factions, \"teleport trapping\" other players is not permitted. Do not take advantage of other players by partaking in such activities.",
            LangConstants::FORMS_PROFILE_RULES_13 => '§e10. Keep your clicks at an acceptable rate',
            LangConstants::FORMS_PROFILE_RULES_13_DESCRIPTION => '§7Spare a thought for the players on PE clients while you are in the game. Jitter clicking is allowed, however butterfly clicking (using two fingers for the same button) and drag clicking (dragging your finger along the surface of the button) is not allowed. Hardware or software that enables you to click at an unacceptable rate is also prohibited. Help us keep the game fair for both mobile and desktop players.',
            LangConstants::FORMS_PROFILE_RULES_14 => '§e11. Report a bug instead of abusing it',
            LangConstants::FORMS_PROFILE_RULES_14_DESCRIPTION => '§7Abusing a bug that gives you an advantage in the game is prohibited, even if you have already reported it to our team. If you find such game breaking bugs, you are asked to report it to #bugs on our Discord server (§bngmc.co/d§7) immediately and to file reports for players who are using these bugs to their advantage.',
            LangConstants::FORMS_PROFILE_RULES_15 => '§e12. Accept the punishment',
            LangConstants::FORMS_PROFILE_RULES_15_DESCRIPTION => '§7Attempting to evade your punishment, or providing assistance to another player to evade theirs, is strictly prohibited. There are rules and an appropriate warning system in place and by using/playing on our services, you agree to follow these set guidelines to help ensure that everyone has a positive experience.',
            LangConstants::FORMS_PROFILE_RULES_16 => '§e13. Speak in English',
            LangConstants::FORMS_PROFILE_RULES_16_DESCRIPTION => "§7We strive to be inclusive of all players regardless of their background or where they come from. We ask that you help us in achieving this goal by speaking in English, which is widely spoken and used around the world.\nThere are exceptions made for players who have difficulty communicating in English.",
            LangConstants::FORMS_PROFILE_RULES_17 => "§bIf you are unsure about what type of activity or behaviour is allowed, we encourage you to contact our support team. We would rather you ask questions to help clear up any misconceptions you may have than to face potential consequences if you do break one of our regulations.\nKeep in mind that the rules here are listed as a reference only. You may find the latest version at §engmc.co/tac§b.",
            LangConstants::FORMS_PROFILE_RULES_18 => '§bWe reserve the right to make changes to these rules at anytime without prior notice or consultation with the wider community, which may come into effect immediately. We may also exercise the right to ban and refuse service or limit service accessibility to any player/user at our discretion, regardless of whether they have broken the regulations listed above.',
            LangConstants::FORMS_PROFILE_RULES_19 => '§bNeed help, or have questions? Contact a staff member using §e/tell§b, through §engmc.co/lc§b, §e@NetherGamesMC §bon Twitter or §esupport@nethergames.org§b.',
            LangConstants::FORMS_PROFILE_RULES_20 => '§bThanks for playing on §eNether§6Games§b!',

            LangConstants::FORMS_PROFILE_KILLS => '&bKills: %0',
            LangConstants::FORMS_PROFILE_DEATHS => '&bDeaths: %0',
            LangConstants::FORMS_PROFILE_LEVEL => '&bLevel: %0',
            LangConstants::FORMS_PROFILE_CREDITS => '&bCredits: %0',
            LangConstants::FORMS_PROFILE_XP => '&bXP: %0',
            LangConstants::FORMS_HANDLER_SETTINGS_ALLOWING => 'allowing',
            LangConstants::FORMS_HANDLER_SETTINGS_BLOCKING => 'blocking',
            LangConstants::FORMS_HANDLER_SETTINGS_DISABLED => 'Disabled',
            LangConstants::FORMS_HANDLER_SETTINGS_ENABLED => 'Enabled',
            LangConstants::FORMS_HANDLER_SETTINGS_FLY_ENABLED => '&aEnabled flying in the lobby',
            LangConstants::FORMS_HANDLER_SETTINGS_FLY_DISABLED => '&aDisabled flying in the lobby',
            LangConstants::FORMS_HANDLER_SETTINGS_FLY_HIDING_RANK => "&cYou can't fly while you're using a nickname or hiding your rank",
            LangConstants::FORMS_HANDLER_SETTINGS_FRIENDS => '&aYou are now &b%0 &afriend requests',
            LangConstants::FORMS_HANDLER_SETTINGS_GUILD_TAG => '&aYou are now &b%0 &ayour guild tag',
            LangConstants::FORMS_HANDLER_SETTINGS_HIDE_PLAYERS => '&aYou are now &b%0 &aplayers',
            LangConstants::FORMS_HANDLER_SETTINGS_HIDING => 'hiding',
            LangConstants::FORMS_HANDLER_SETTINGS_KNOCKBACK => '&a%0 knockback in the lobby',
            LangConstants::FORMS_HANDLER_SETTINGS_NICK_ENABLED => '&aYour name tag has been changed to &b%0&a!',
            LangConstants::FORMS_HANDLER_SETTINGS_NICK_RESET => '&aReset your name tag',
            LangConstants::FORMS_HANDLER_SETTINGS_NICK_ALREADY => '&cAn account with that username already exists, please try again',
            LangConstants::FORMS_HANDLER_SETTINGS_DM_ALL => '&aYou are now allowing direct messages from all players',
            LangConstants::FORMS_HANDLER_SETTINGS_DM_FRIENDS => '&aYou are now allowing direct messages from friends only',
            LangConstants::FORMS_HANDLER_SETTINGS_DM_BLOCK => '&cYou are now blocking all direct messages from everyone',
            LangConstants::FORMS_HANDLER_SETTINGS_PET_SELECTED => '&aYour pet has been changed to a &b%0',
            LangConstants::FORMS_HANDLER_SETTINGS_PET_REMOVED => '&aYour pet has been removed',
            LangConstants::FORMS_HANDLER_SETTINGS_PET_INVALID => '&cThat\'s an invalid pet name. Please choose another one',
            LangConstants::FORMS_HANDLER_SETTINGS_RANK_HIDING => '&aYour rank is now &bhiding',
            LangConstants::FORMS_HANDLER_SETTINGS_RANK_SHOWING => '&aYour rank is now &bshowing',
            LangConstants::FORMS_HANDLER_SETTINGS_SHOWING => 'showing',
            LangConstants::FORMS_HANDLER_REPORTER_REPORTED => '&aYou have successfully reported &b%0 &cfor &a%1',
            LangConstants::FORMS_HANDLER_REPORTER_NOT_REPORTED => '&cThis player cannot be reported',
            LangConstants::FORMS_HANDLER_REPORTER_STAFF_MESSAGE => '&b%0 &6has been reported by %1 for &c%2',

            LangConstants::FORMS_REPORTER => '§cReporter',

            LangConstants::FORMS_SETTINGS_TITLE => '&bSettings',
            LangConstants::FORMS_SETTINGS_PREFERENCES => '&bPreferences',
            LangConstants::FORMS_SETTINGS_CHANGE => "Change your pet's name: (Use \"off\" or \"reset\" to reset to default)",
            LangConstants::FORMS_SETTINGS_FLY => 'Toggle fly',
            LangConstants::FORMS_SETTINGS_FRIENDS => 'Allow friend requests',
            LangConstants::FORMS_SETTINGS_HIDE_GUILD_TAG => 'Hide guild tag',
            LangConstants::FORMS_SETTINGS_HIDE_PLAYERS => 'Show/hide players',
            LangConstants::FORMS_SETTINGS_HIDE_RANK => 'Hide rank',
            LangConstants::FORMS_SETTINGS_KNOCKBACK => 'Toggle knockback',
            LangConstants::FORMS_SETTINGS_NICK => 'Change your nick: (Use "off" or "reset" to reset to default)',
            LangConstants::FORMS_SETTINGS_FPS => 'Low FPS mode',
            LangConstants::MESSAGES_SETTINGS_FPS_ENABLED => '&aEnabled low FPS mode. You will no longer see fancy graphics and animations',
            LangConstants::MESSAGES_SETTINGS_FPS_DISABLED => '&cDisabled low FPS mode. You will now see fancy graphics and animations',
            LangConstants::FORMS_SETTINGS_REGION => 'Region queuing',
            LangConstants::MESSAGES_SETTINGS_REGION_ENABLED => '&aEnabled region queuing. You will now queue to servers that are in the same region as the proxy you are connected to',
            LangConstants::MESSAGES_SETTINGS_REGION_DISABLED => '&cDisabled region queuing. You will now queue to servers on both regions',
            LangConstants::FORMS_SETTINGS_TOUCH => 'Touch queuing',
            LangConstants::MESSAGES_SETTINGS_TOUCH_ENABLED => '&aEnabled touch only queuing. You will now only queue with other players who use touch controls. This may extend the waiting time for matches',
            LangConstants::MESSAGES_SETTINGS_TOUCH_DISABLED => '&cDisabled touch only queuing. You will no longer only queue with other players who use touch controls',
            LangConstants::FORMS_SETTINGS_POPUP => 'Popup game messages',
            LangConstants::MESSAGES_SETTINGS_POPUP_ENABLED => '&aEnabled popup game messages. Applicable messages will now be shown as popups in-game to prevent spam',
            LangConstants::MESSAGES_SETTINGS_POPUP_DISABLED => '&cDisabled popup game messages. Applicable messages will no longer be shown as popups in-game',
            LangConstants::FORMS_SETTINGS_BW_SLIDER => 'BedWars slider',
            LangConstants::MESSAGES_SETTINGS_BW_SLIDER_ENABLED => '&aEnabled the Bedwars slider. You will now be able to select an amount when purchasing from the shop',
            LangConstants::MESSAGES_SETTINGS_BW_SLIDER_DISABLED => '&cDisabled the Bedwars slider. You will no longer be able to select an amount when purchasing from the shop',
            LangConstants::FORMS_SETTINGS_BW_CHEST => 'BedWars Chest UI',
            LangConstants::MESSAGES_SETTINGS_BW_CHEST_ENABLED => '&aEnabled the Bedwars chest UI. You will now be shown a chest inventory interface when using the shop and upgrader',
            LangConstants::MESSAGES_SETTINGS_BW_CHEST_DISABLED => '&cDisabled the Bedwars chest UI. You will now be shown a form interface when using the shop and upgrader',
            LangConstants::FORMS_SETTINGS_BW_NPC => 'BedWars left-click NPCs',
            LangConstants::MESSAGES_SETTINGS_BW_NPC_ENABLED => '&aEnabled left click NPCs in Bedwars. You will now be able to use both left click and right click to activate the shop and upgrader',
            LangConstants::MESSAGES_SETTINGS_BW_NPC_DISABLED => '&cDisabled left click NPCs in Bedwars. You will no longer be able to use left click to activate the shop and upgrader',
            LangConstants::FORMS_SETTINGS_PVP => 'PvP Damage Display',
            LangConstants::MESSAGES_SETTINGS_PVP_ENABLED => '&aEnabled damage displays. You will now be able to see how much damage you deal to opponents and their health when you hit them',
            LangConstants::MESSAGES_SETTINGS_PVP_DISABLED => '&cDisabled damage displays. You will no longer be able to see how much damage you deal to opponents and their health when you hit them',
            LangConstants::FORMS_SETTINGS_NAMETAG => 'Nametag',
            LangConstants::FORMS_SETTINGS_NICK_2 => 'Select a nick:',
            LangConstants::FORMS_SETTINGS_DM => 'DM Privacy Settings',
            LangConstants::FORMS_SETTINGS_DM_ALL => 'Allow from all',
            LangConstants::FORMS_SETTINGS_DM_FRIENDS => 'Allow only from friends',
            LangConstants::FORMS_SETTINGS_DM_BLOCK => 'Block all messages',
            LangConstants::FORMS_SETTINGS_PETS => '&bPets',
            LangConstants::FORMS_SETTINGS_PET => 'Your pet:',
            LangConstants::FORMS_SETTINGS_PET_SET_NAME => "&aYour pet's name has been changed to &b%0&a!",
            LangConstants::FORMS_SETTINGS_LANGUAGE => 'Language',

            LangConstants::FORMS_TELEPORTER => '&eNether&6Games &bTeleporter',
            LangConstants::FORMS_TELEPORTER_FULL => '&cFULL',
            LangConstants::FORMS_TELEPORTER_OFFLINE => '&cOFFLINE',
            LangConstants::FORMS_TELEPORTER_SELECT => 'Select a minigame:',
            LangConstants::FORMS_TELEPORTER_PARTLY => '&6PARTLY ONLINE',
            LangConstants::FORMS_MINIGAMES_BACK_TO_SPAWN => '&cBack to spawn',

            LangConstants::FORMS_SERVERS_CONNECT => '%0 %1 &7[&2%2&7/&2%3&7] &eYou are on this server',
            LangConstants::FORMS_SERVERS_HERE => '%0 %1 &7[&2%2&7/&2%3&7] &eClick to connect',

            LangConstants::FORMS_TRACK_TITLE => 'Track menu',
            LangConstants::FORMS_TRACK_SELECT_PLAYER => 'Select player:',
            LangConstants::FORMS_TRACK_TP_TO => 'Teleport to %0',
            LangConstants::MESSAGES_TRACK_ALREADY_TRACKING => '&cYou are not in tracking mode',
            LangConstants::MESSAGES_TRACK_PLAYER_OFFLINE => '&cThat player is not in this server anymore',

            LangConstants::MENU_BLOCKED => "&cYou don't have permission to use that menu.",
            LangConstants::PARTICIPATION => 'Participation',

            LangConstants::WIN_STREAK_GAIN => "&6You're on a winning streak of &b%0&6!",
            LangConstants::WIN_STREAK_ACHIEVE => "&aYou've achieved a new best streak of &6&a!",
            LangConstants::WIN_STREAK_LOST => '&cWinning streak lost!',

            LangConstants::STATS_WIN => 'Win',
            LangConstants::STATS_KILL => 'Kills',
            LangConstants::STATS_BOOST => 'boost (%0 in game)',
            LangConstants::STATS_BOOST_VOTER => 'boost (Voter reward)',

            LangConstants::PLAYER_OFFLINE => "&cThat player isn't online.",
            LangConstants::PLAYER_NOT_EXIST => '&cThat player doesn\'t exist',
            LangConstants::KICK_ALREADY => '&o&l&eN&6G&r&7: &cYour account is already logged onto the network. Please try again later',
            LangConstants::KICK_PROXY => '§o§l§eN§6G§r§7: §cUsing a proxy to play on §eNether§6Games §cis not allowed. Disable it to play!',
            LangConstants::SKIN_NOT_VALID_REJOIN => "&cYour skin is not valid to play on &eNether&6Games&c.\nPlease choose another one and rejoin.",
            LangConstants::IMPERSONATING_STAFF => '&cImpersonating staff members is not allowed.',
            LangConstants::NICKNAME_DISALLOWED => "&cYou're not allowed to use that name",
            LangConstants::VOTE_CLAIMED => "&cYou've already voted and claimed your rewards today.",
            LangConstants::VOTE_CLAIMING => '&6Thanks for voting! Claiming your rewards...',
            LangConstants::VOTE_ERROR => '&cAn unknown error occurred while checking your vote status.',
            LangConstants::VOTE_NOT_YET => "&cYou haven't voted yet today. Vote at &bngmc.co/v&c, then come back and claim your rewards.",
            LangConstants::VOTE_SUCCESSFUL => '&aSuccessfully claimed your rewards. Thanks for voting for &eNether&6Games&a!',
            LangConstants::WORLD_VOTE => '&cYou must vote to access Mega creative',
            LangConstants::XP_SUMMARY => "&6&lExperience Summary: \n",
            LangConstants::JOIN_VOTE => '&6Vote for us daily at &bngmc.co/v &6and you could win a free rank upgrade!',
            LangConstants::JOIN_WELCOME => '&bWelcome to §eNether&6Games&b!',

            LangConstants::PETS_CROUCH => '&7Crouch or jump to dismount...',
            LangConstants::PETS_RIDE_NO_PERM => "&cYou don't have permission to ride and control pets.\n&cYou can buy the &l&cTITAN&r §crank at &bngmc.co/store &cto ride them!",
            LangConstants::PARKOUR_NO_FLY => '&cYou can\'t enable flying while you\'re attempting the parkour',


            LangConstants::PLACE_1 => '&l&e1st Place &r&7- &b%0 - &e%1',
            LangConstants::PLACE_2 => '&l&62nd Place &r&7- &b%0 - &e%1',
            LangConstants::PLACE_3 => '&l&c3rd Place &r&7- &b%0 - &e%1',
            LangConstants::PLACE_X => '&e#%0 &r&b%1 - &e%2',

            LangConstants::FORMS_PUNISH_PERM => '&cYou don\'t have permissions to punish players',


            LangConstants::AFK_KICK => '&o&l&eN&6G&r&7: &cYou have been kicked for being inactive for a while. Buy the &l&aEMERALD &r&cor &l&bLEGEND &r&crank at &bngmc.co/store &cto remove this restriction!',
            LangConstants::AFK_INACTIVE => '&cYou have been transferred to the lobby for being inactive in a game. Credit farming is not allowed and offenders may be issued warnings.',
            LangConstants::AFK_INACTIVE_RANK => '&cYou have been transferred to the lobby for being inactive for a while. Buy the &l&aEMERALD &r&cor &l&bLEGEND &r&crank at &bngmc.co/store §cto remove this restriction!',
            LangConstants::NEAREST_PLAYER => '&6Closest player: &b%0 &6| Distance: &b%1',
            LangConstants::PLAYER_IN_QUEUE => '&6You are &b#%0 &6in the queue!',

            LangConstants::TRANSFER_QUEUE_JOIN => '&6The server is currently full and you have been placed in a queue. \n&6Buy the &l&aEMERALD&r &6or &l&bLEGEND&r &6rank at &bngmc.co/store &6to skip the queue!',
            LangConstants::TRANSFER_QUEUE_LEFT => '&aSuccessfully left the queue!',
            LangConstants::TRANSFER_SERVER_OFFLINE => '&cThat server is currently offline. Please try again later',
            LangConstants::REGION_LACK_PLAYER => '&cThe %0 region is currently disabled due to a lack of players. Region queuing settings will be ignored',
            LangConstants::REGION_FULL => '&cThe %0 region is currently full and you have been placed in a queue',
            LangConstants::REGION_FULL_RANK => '&6Buy the &l&aEMERALD&r &6or &l&bLEGEND&r &6rank at &bngmc.co/store &6to skip the queue!',

            LangConstants::PARKOUR_NEW_RECORD_SERVER => '&l&6CONGRATULATIONS! &r&aYou have broken new record for the parkour with a time of &b%0 &a- you can view the parkour leaderboards online at &6ngmc.co/a',
            LangConstants::PARKOUR_NEW_RECORD_PERSONAL => '&l&6NEW PERSONAL RECORD! &r&aYou have broken your personal record for the parkour with a time of &e%0&a. Your previous time was &e%1&a.',
            LangConstants::PARKOUR_STARTED => "&aYou've started the parkour attempt!",
            LangConstants::PARKOUR_CHECKPOINT_REACHED => '&aYou reached checkpoint &7#%0 &ain %1',
            LangConstants::PARKOUR_FINISHED => '&aYou completed parkour in &e%0&a. Your record is &e%1',
            LangConstants::PARKOUR_NO_CHEATING => '&cCheating on the parkour course is not allowed! If you ever make this again, you will be punished!!',
            LangConstants::PARKOUR_COMMAND => '&cYou can\'t run this command while you\'re attempting the parkour',
            LangConstants::PARKOUR_ABANDONED => '&aYou abandoned the parkour attempt',

            LangConstants::PRESENTS_FOUND => '&aYou found a Present! &7($0/%1) %2 more presents to collect!',
            LangConstants::PRESENTS_FOUND_ALL => '&aFind all the presents to get a reward!',
            LangConstants::PRESENTS_FOUND_CAPE => '&aYou have received your new christmas cape',
            LangConstants::PRESENTS_FOUND_CONGRATS => '&aCongratulations! You found all the presents',

            LangConstants::FORMS_SOCIAL => 'Social Menu',
            LangConstants::FORMS_SOCIAL_INVITED => 'Social Menu - %0',
            LangConstants::FORMS_SOCIAL_MAIN_FRIENDS => '&bFriends',
            LangConstants::FORMS_SOCIAL_MAIN_FRIENDS_INVITES_SINGLE => '\n&71 friend invite',
            LangConstants::FORMS_SOCIAL_MAIN_FRIENDS_INVITES_MULTIPLE => '\n&7%0 friend invites',
            LangConstants::FORMS_SOCIAL_MAIN_GUILDS => '&aGuilds',
            LangConstants::FORMS_SOCIAL_MAIN_GUILDS_ALREADY_IN => '\n&7You are in %0 guild',
            LangConstants::FORMS_SOCIAL_MAIN_GUILDS_INVITES_SINGLE => '\n&71 guild invite',
            LangConstants::FORMS_SOCIAL_MAIN_GUILDS_INVITES_MULTIPLE => '\n&7%0 guild invites',
            LangConstants::FORMS_SOCIAL_MAIN_PARTY => '&eParty',
            LangConstants::FORMS_SOCIAL_MAIN_PARTY_ALREADY_IN_OWN => '\n&7You are in your own party',
            LangConstants::FORMS_SOCIAL_MAIN_PARTY_ALREADY_IN_OTHER => "\n&7You are in %0's party",
            LangConstants::FORMS_SOCIAL_MAIN_PARTY_INVITES_SINGLE => '\n&71 friend invite',
            LangConstants::FORMS_SOCIAL_MAIN_PARTY_INVITES_MULTIPLE => '\n&7%0 friend invites',

            LangConstants::FORMS_SOCIAL_INVITE_FRIEND => '&eAdd as friend\n&7Send request to %0',
            LangConstants::FORMS_SOCIAL_INVITE_PARTY => '&eInvite to party\n&7Invite %0 your party',
            LangConstants::FORMS_SOCIAL_VIEW_STATS => "&eCheck stats\n&7View %0's statistics",
            LangConstants::FORMS_HANDLER_SOCIAL_INVITE_NO_PERM => "&cYou don't have permission to add more friends! Buy a rank at &bngmc.co/store &cto add more!",

            LangConstants::FORMS_SOCIAL_FRIENDS_MENU_TITLE => 'Friends',
            LangConstants::FORMS_SOCIAL_FRIENDS_MENU_LIST => '&eFriend list\n&7Online: &a%0 &7| Total: &a%1/%2',
            LangConstants::FORMS_SOCIAL_FRIENDS_MENU_ADD => '&eAdd friend',
            LangConstants::FORMS_SOCIAL_FRIENDS_MENU_REQUESTS => '&eFriend requests\n&7Current requests: &a%0',
            LangConstants::FORMS_SOCIAL_FRIENDS_LIST_ONLINE_HERE => '&e%0\n&aOnline on this server',
            LangConstants::FORMS_SOCIAL_FRIENDS_LIST_ONLINE_THERE => '&e%0\n%aOnline on %1',
            LangConstants::FORMS_SOCIAL_FRIENDS_LIST_OFFLINE => '&e%0\n&cOffline',
            LangConstants::FORMS_SOCIAL_FRIENDS_SUMMARY_TITLE => 'Friend: %0',
            LangConstants::FORMS_SOCIAL_FRIENDS_SUMMARY_INVITE_TO_PARTY => '&eInvite to party\n&7Send a party invite',
            LangConstants::FORMS_SOCIAL_FRIENDS_SUMMARY_GO_TO_SERVER => '&eGo to server\n&7Transfers you to the player',
            LangConstants::FORMS_SOCIAL_FRIENDS_SUMMARY_SPECTATE => '&eSpectate player\n&7Watch in spectator mode',
            LangConstants::FORMS_HANDLER_SOCIAL_FRIENDS_SUMMARY_SPECTATE => "&cYou don't have permission to spectate friends. Buy the &l&cTITAN &r&crank at &bngmc.co/store &cto use this feature!",
            LangConstants::FORMS_SOCIAL_FRIENDS_SUMMARY_UNFRIEND => '&eRemove\n&7Unfriend %0',
            LangConstants::FORMS_SOCIAL_FRIENDS_SUMMARY_UNFRIEND_TITLE => '&cRemove friend',
            LangConstants::FORMS_SOCIAL_FRIENDS_SUMMARY_UNFRIEND_CONTENT => 'Do you want to remove %0 as a friend?',
            LangConstants::FORMS_HANDLER_SOCIAL_FRIENDS_SUMMARY_UNFRIEND => '&You have successfuly removed &b%0 &aas a friend',
            LangConstants::FORMS_HANDLER_SOCIAL_FRIENDS_SUMMARY_UNFRIEND_RECEIVER => '&b%0 %cremoved you as a friend',
            LangConstants::FORMS_SOCIAL_FRIENDS_REQUESTS_TITLE => 'Friend requests',
            LangConstants::FORMS_SOCIAL_FRIENDS_REQUESTS_CONTENT => 'You currently have %0 pending friend requests:',
            LangConstants::FORMS_SOCIAL_FRIENDS_REQUESTS_AOD => '&e%0\n&7Accept or deny request',
            LangConstants::FORMS_SOCIAL_FRIENDS_REQUESTS_PERM => '&cYou don\'t have permission to add more friends! Buy a rank at &bngmc.co/store &cto add more!',
            LangConstants::FORMS_SOCIAL_FRIENDS_REQUESTS_QUESTION => 'Do you want to friend %0?',
            LangConstants::FORMS_SOCIAL_FRIENDS_REQUESTS_ALREADY => '&cYou\'re already friends with that player',
            LangConstants::FORMS_SOCIAL_FRIENDS_REQUESTS_ACCEPT_RECEIVER => '&aYou are now friends with &b%0&a!',
            LangConstants::FORMS_SOCIAL_FRIENDS_REQUESTS_ACCEPT_SENDER => '&b%0 &aaccepted your friend request, wohoo',
            LangConstants::FORMS_SOCIAL_FRIENDS_REQUESTS_DENY_RECEIVER => '&cDeclined the friend request from &b%0',
            LangConstants::FORMS_SOCIAL_FRIENDS_REQUESTS_DENY_SENDER => '&b%0 &cdeclined your friend request',
            LangConstants::FORMS_SOCIAL_FRIENDS_REQUESTS_ANY => 'You haven\'t any friend requests',
            LangConstants::FORMS_SOCIAL_FRIENDS_ADD_TITLE => 'Add a friend',
            LangConstants::FORMS_SOCIAL_FRIENDS_ADD_SELECT => 'Select a player',
            LangConstants::FORMS_SOCIAL_FRIENDS_ADD_PERM => '&cYou don\'t have permission to add more friends! Buy a rank at &bngmc.co/store &cto add more',
            LangConstants::FORMS_SOCIAL_FRIENDS_SEND_CANNOT => '&cThat player can\'t add any more friends',
            LangConstants::FORMS_SOCIAL_FRIENDS_SEND_ALREADY => '&cYou\'ve already sent a friend request to &b%0',
            LangConstants::FORMS_SOCIAL_FRIENDS_SEND_BLOCKED => '&b%0 &chas blocked friend requests. Ask them to allow friend requests to add them as a friend',
            LangConstants::FORMS_SOCIAL_FRIENDS_SEND_RECEIVER => '&b%0 &arequested to be as your friend. Use Social Menu to accept or deny this request',
            LangConstants::FORMS_SOCIAL_FRIENDS_SEND_SENDER => '&aSent friend request to &b%0',


            LangConstants::FORMS_SOCIAL_PARTY_MENU_TITLE => 'Party Menu',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_CREATE => '&eCreate a party',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_PUBLIC => '&ePublic parties\n&7Available parties: %0',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_PUBLIC_TITLE => '&ePublic parties',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_PUBLIC_LEADER => '&e%0\'s Party \n&7Join %0\'s party',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_INVITES => '&eView invites\n&7Current invites: %0',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_INVITES_TITLE => 'View invites',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_INVITES_LEADER => '&e%0\'s Party \n&7Join %0\'s party',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_MEMBERS => '&eParty members\n&7Members: &a%0/%1',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_MEMBERS_INVITE => '&eInvite players',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_MEMBERS_INVITE_TITLE => 'Invite players',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_MEMBERS_INVITE_MORE => 'Invite more players: ',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_SETTINGS => '&eSettings',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_SETTINGS_TITLE => 'Settings',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_SETTINGS_PUBLIC => 'Public party',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_SETTINGS_PUBLIC_ENABLED => '&aEnabled public party. All players on the same server as you will now be able to join your party',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_SETTINGS_PUBLIC_DISABLED => '&cDisabled public party. You will now need to invite players to join your party',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_SETTINGS_PRIVATE => 'Private games',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_SETTINGS_PRIVATE_ENABLED => '&aEnabled private games. Your party will now be queued into a separate match without any other players upon joining a game',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_SETTINGS_PRIVATE_DISABLED => '&cDisabled private games. Your party will no longer be queued into a separate match upon joining a game',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_SETTINGS_RANDOM => 'Enable player randomization',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_SETTINGS_RANDOM_ENABLED => '&aEnabled player randomisation. Players will be put into random teams in your match',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_SETTINGS_RANDOM_DISABLED => '&cDisabled player randomisation. Players will no longer be put into random teams',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_DISBAND => '&eDisband the party',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_DISBAND_TITLE => 'Disband the party',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_DISBAND_CONTENT => 'Are you sure to disband the party?',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_LEAVE => '&eLeave party',
            LangConstants::FORMS_SOCIAL_PARTY_MENU_LEAVE_CONTENT => 'Are you sure to leave %0\'s party?',
            LangConstants::FORMS_SOCIAL_PARTY_MEMBERS => 'Party members',
            LangConstants::FORMS_SOCIAL_PARTY_MEMBERS_LEADER => '&e%0 Party leader',
            LangConstants::FORMS_SOCIAL_PARTY_MEMBERS_MEMBER => 'Party member: %0',
            LangConstants::FORMS_SOCIAL_PARTY_MEMBERS_MEMBER_KICK => '&eKick member\n&7Remove them from the party',
            LangConstants::FORMS_SOCIAL_PARTY_MEMBERS_MEMBER_PROMOTE => '&ePromote member\n&7Make them party leader',

            LangConstants::PARTY_NO_LONGER_HERE => '&cThat party is no longer on this server',
            LangConstants::PARTY_WELCOME => '&6Welcome to &b%0\'s &6party',
            LangConstants::PARTY_JOIN => '&b%0 &7joined the party!',
            LangConstants::PARTY_FULL => '&cThat party is currently full',
            LangConstants::PARTY_NOT_HOSTING => '&cYou are not hosting a party!',
            LangConstants::PARTY_ALREADY_INVITED => '&cYou have already invited &b%0',
            LangConstants::PARTY_ALREADY_IN_HOST => '&b%0 &cis already in a party!',
            LangConstants::PARTY_MAX => '&cYou can\'t invite more of &65 &cthan in your party',
            LangConstants::PARTY_INVITED => '&aInvited &b%0 &ato your party!',
            LangConstants::PARTY_INVITE => '&b%0 &ahas invited you to join your party. Use Social Menu to view invite',
            LangConstants::PARTY_ENDED_HOST => '&aEnded your party',
            LangConstants::PARTY_ENDED => '&b%0 &ahas ended their party. Thanks for playing!',
            LangConstants::PARTY_LEAVE_PLAYER => '&aYou left the party',
            LangConstants::PARTY_LEAVE => '&b%0 &ahas left our party. Wish him good luck!',
            LangConstants::PARTY_STILL_IN_GAME => '&b%0 &cis still in a match! Please wait for them before you join another one!',
            LangConstants::PARTY_TRACKING => '&b%0 &cis tracking someone.Please wait for them to leave!',
            LangConstants::PARTY_JOIN_GAME => "&cYou're currently in a party. Wait for your party host to decide which game to play!",
            LangConstants::PARTY_PROMOTED => '&6%0 &ahas been promoted to a party leader',
            LangConstants::PARTY_KICKED => '&cYou have been kicked from the party by &b%0&c.',
            LangConstants::PARTY_KICKED_MESSAGE => '&b%0 &6kicked &c%1 &6from the party.',

            LangConstants::FORMS_SOCIAL_GUILD_MENU_TITLE => 'Guild Menu',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_MEMBERS => '&eGuild members\n&7Online: &a%0 &7| Members: &a%1/%2',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_STATS => '&eGuild statistics',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_STATS_XP => '&6%0 XP required to reach next level',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_MEMBERS_INVITE => 'Invite player',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_MEMBERS_INVITE_MORE => 'Invite more players: ',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_MOTD => '&eEdit MOTD',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_MOTD_TITLE => 'Set Guild MOTD',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_MOTD_INPUT => 'Enter a MOTD:',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_MOTD_LABEL => 'Your guild MOTD is displayed to your guild members everytime they join the server.',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_TAG => '&eChange guild tag',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_TAG_TITLE => 'Set guild tag',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_TAG_DROPDOWN => 'Choose a colour:',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_TAG_INPUT => 'Enter a tag:',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_TAG_LABEL => 'Your guild tag is displayed at the end of each member\'s nametag in the lobby and can\'t be more than 6 characters long.',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_DISBAND => '&eDisband the guild',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_DISBAND_TITLE => 'Disband guild',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_DISBAND_CONTENT => 'Are you sure to disband %0 guild? This action is irreversible',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_LEAVE => '&eLeave the guild',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_LEAVE_TITLE => 'Leave guild',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_LEAVE_CONTENT => 'Are you sure leave the %0 guild?',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_CREATE => '&eCreate the guild',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_CREATE_TITLE => 'Create Guild',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_CREATE_NAME => 'Enter you desired guild name:',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_INVITES => '&eView invites\n&7Current invites: %0',
            LangConstants::FORMS_SOCIAL_GUILD_MENU_INVITES_TITLE => 'Guild invites',
            LangConstants::FORMS_SOCIAL_GUILD_MEMBERS => 'Guild Members',
            LangConstants::FORMS_SOCIAL_GUILD_MEMBERS_LEADER => '&e%0\n&7Leader | ',
            LangConstants::FORMS_SOCIAL_GUILD_MEMBERS_OFFICER => '&e%0\n&7Officer | ',
            LangConstants::FORMS_SOCIAL_GUILD_MEMBERS_ONLINE => '&aOnline',
            LangConstants::FORMS_SOCIAL_GUILD_MEMBERS_OFFLINE => '&cOffline',
            LangConstants::FORMS_SOCIAL_GUILD_MEMBER_TITLE => 'Guild member: %0',
            LangConstants::FORMS_SOCIAL_GUILD_MEMBER_PROMOTE_TO_LEADER => '&ePromote to Leader\n&7Make them the guild leader',
            LangConstants::FORMS_SOCIAL_GUILD_MEMBER_PROMOTE_TO_OFFICER => '&ePromote to Officer\n&7Make them the guild officer',
            LangConstants::FORMS_SOCIAL_GUILD_MEMBER_DEMOTE_TO_MEMBER => '&eDemote to Member\n&7Make them guild member again',
            LangConstants::FORMS_SOCIAL_GUILD_MEMBER_KICK => '&eKick\n&7Remove them from the guild',

            LangConstants::GUILD_LOW_LEVEL => 'cYour guild must be at least level %0 to use this feature!',
            LangConstants::GUILD_MOTD_SET => '&aYour guild motd has been set',
            LangConstants::GUILD_MOTD_RESET => '&aYour guild MOTD has been reset',
            LangConstants::GUILD_TAG_CHARS => '&cYour guild tag can\'t be more than 6 characters long.',
            LangConstants::GUILD_TAG_COLORS => '&aYour guild tag has been set to &l%0 &r&a!',
            LangConstants::GUILD_JOIN => '&aWelcome to the &b%0 &aguild!',
            LangConstants::GUILD_JOIN_PLAYERS => '&b%0 &ahas joined our guild',
            LangConstants::GUILD_LEAVE => '&aYou left &b%0 &aguild',
            LangConstants::GUILD_LEAVE_PLAYERS => '&b%0 &ahas left out guild',
            LangConstants::GUILD_CREATE_PERM => '&cYou don\'t have permission to create a guild! Buy the §l§bLEGEND §r§crank at §bngmc.co/store §cto create one',
            LangConstants::GUILD_PROMOTE_LEADER => '&b%0 &ahas been promoted to guild leader.',
            LangConstants::GUILD_PROMOTE_LEADER_ONLINE => '&cThat player must be online for them to transfer leadership of the guild',
            LangConstants::GUILD_PROMOTE_LEADER_PERM => '&cThat player does not have the required permissions to take leadership of the guild',
            LangConstants::GUILD_PROMOTE_OFFICER => '&b%0 &ahas been promoted to guild officer',
            LangConstants::GUILD_DEMOTE_MEMBER => '&b%0 &ahas been demoted to guild member',
            LangConstants::GUILD_KICK => '&cYou have been kicked from &b%0 &cby &b%1',
            LangConstants::GUILD_KICK_PLAYERS => '&b%0 &akicked &b%1 &afrom the guild',
            LangConstants::GUILD_ALREADY_INVITED => '&cYou have already &b%0 &cto &b%1',
            LangConstants::GUILD_ALREADY_IN_GUILD => '&b0 &cis already in guild',
            LangConstants::GUILD_INVITE_CANNOT => '&cYou can\'t invite more than &6%0 &cto &b%1',
            LangConstants::GUILD_INVITE => '&aInvited &b%0 &ato &b%1 &aguild',
            LangConstants::GUILD_INVITE_PLAYER => '&b%0 &6has invited you to join &b%1 &6guild! Use Social Menu to view invite',
            LangConstants::GUILD_DISBAND => '&aDisbanded the &b%0 &aguild!',
            LangConstants::GUILD_DISBAND_PLAYERS => '&b%0 &ahas disbanded the &b%1 &aguild',
            LangConstants::GUILD_NAME_ALREADY => '&cA guild with that name already exists',


            LangConstants::MINIGAME_JOIN_ALREADY => '&cYou\'re already in %0 match!',
            LangConstants::MINIGAME_JOIN_TRACKING => '&cYou\'re currently in tracking mode. Leave to join the game',
            LangConstants::MINIGAME_JOIN_PARTY_BIG => '&cYour party is too big to join this game. Pleasy try again later',
            LangConstants::MINIGAME_ADD_TRACKING => '&c%0 is in tracking someone. Wait for them to leave',
            LangConstants::MINIGAME_QUIT_FORM => 'Quit the match',
            LangConstants::MINIGAME_QUIT_FORM_SINGLE => '%0 is still in game. Are you sure you wish take them to the lobby?',
            LangConstants::MINIGAME_QUIT_FORM_MULTIPLE => '%0 are still in game. Are you sure you wish take them all to the lobby?',
            LangConstants::MINIGAME_QUIT_PARTY_GAME => '&cYou cannot go back to the loby while you\'re in a party. Please for party leader until he decides when to leave',
            LangConstants::MINIGAME_QUIT_DISCONNECTED_PLAYERS => '%0 &7disconnected',
            LangConstants::MINIGAME_QUIT_DISCONNECTED => '&aYou left the game',
            LangConstants::MINIGAME_QUIT_LEFT => '%0 &ehas quit!',
            LangConstants::MINIGAME_QUEUE_PRIVATE => '&6You are currently in a private party match. You will only be able to play with people in your party. Players outside of your party will not be able to join this match.',
            LangConstants::MINIGAME_QUEUE_TOUCH => '&6You are currently in a touch controls only match - queuing might take slightly longer. You can play with all players (not only touch control users) by disabling "Touch only queuing" in Profile Settings -> Preferences while in the lobby.',
            LangConstants::MINIGAME_QUEUE_ANY => '&6You are currently playing a match that includes players using any device. You can play matches with touchscreen players only by enabling "Touch only queuing" in Profile Settings -> Preferences while in the lobby.',
            LangConstants::MINIGAME_QUEUE_ADD => '%0 &ehas joined (%1&e/%2&e)!',
            LangConstants::MINIGAME_MAP_WON_SINGLE => '&e%0 &ahas won with &6%1 &avotes',
            LangConstants::MINIGAME_MAP_WON_MULTIPLE => '&e%0 &ahas won with &6%1 &avotes',
            LangConstants::MINIGAME_MAP_RANDOM => '&6%0 &ehas been randomly selected',
            LangConstants::MINIGAME_COMMAND_GAME => '§cYou can\'t run this command while you\'re in a %0 match. Use §b/%1 quit §cto quit the game and run that command.',
            LangConstants::MINIGAME_PARTY_NO_LONGER => '&6%0 &cis no longer on this server',
            LangConstants::MINIGAME_PARTY_NOT_HERE => '&c%0 is not on this server',
            LangConstants::MINIGAME_PARTY_ONE_NOT_HERE => "&cOne of your party members hasn't connected to this server. Joining the game...",
            LangConstants::MINIGAME_PARTY_WAIT => '&cYou can\'t join another game while you\'re in a party. Wait for your party host to decide when to play again!',

            LangConstants::MINIGAME_SCOREBOARD_WAITING => 'Waiting',
            LangConstants::MINIGAME_SCOREBOARD_STARTING => 'Starting in &a%0s',

            LangConstants::MINIGAME_GAME_STARTS_IN => '&eGame starts in %0 &eseconds',
            LangConstants::MINIGAME_GAME_VOTING_ENDED => '&6Voting has ended!',
            LangConstants::MINIGAME_GAME_COUNT_CANCEL => '&cWe don\'t have enough players! Start cancelled',
            LangConstants::MINIGAME_GAME_COUNT_WATING => '&cWaiting for more players...',
            LangConstants::MINIGAME_GAME_BED => '&l&aQueued! Use the bed to return to lobby!',

            LangConstants::MINIGAME_ITEM_COMPASS => '&r&a&lPlayer Locator',
            LangConstants::MINIGAME_ITEM_COMPASS_LORE => '&r&7Use it to locate players',
            LangConstants::MINIGAME_ITEM_COMPASS_SPECTATOR => '&r&a&lTeleporter &r&7(Right Click)',
            LangConstants::MINIGAME_ITEM_COMPASS_SPECTATOR_LORE => '&r&7Right-click to spectate players!',
            LangConstants::MINIGAME_ITEM_QUIT => '&r&c&lReturn to Lobby &7(Right-Click)',
            LangConstants::MINIGAME_ITEM_QUIT_LORE => '&r&7Right-click to leave to the lobby',
            LangConstants::MINIGAME_ITEM_MAPS => '&r&b&lVote for Map &7(Right-Click)',
            LangConstants::MINIGAME_ITEM_MAPS_LORE => '&r&7Right-click to vote for a map',
            LangConstants::MINIGAME_ITEM_REPLAY => '&r&b&lPlay Again &r&7(Right Click)',
            LangConstants::MINIGAME_ITEM_REPLAY_LORE => '&r&7Right-click to play another game!',
            LangConstants::MINIGAME_ITEM_TEAMS => '&r&l%0Change Team &r&7(Right Click)',
            LangConstants::MINIGAME_ITEM_TEAMS_LORE => '&r&7Right-click to select another team!',

            LangConstants::MINIGAME_FORMS_EXIT => '&l&cExit',

            LangConstants::MINIGAME_FORMS_QUIT_TITLE => 'Quit the match',
            LangConstants::MINIGAME_FORMS_QUIT_CONTENT_SINGLE => '%0 is still in game. Are you sure you wish to take them to the lobby?',
            LangConstants::MINIGAME_FORMS_QUIT_CONTENT_MULTIPLE => '%0 are still in game. Are you sure you wish to take them to the lobby?',
            LangConstants::MINIGAME_FORMS_QUIT_REPLAY => 'Play again?',
            LangConstants::MINIGAME_FORMS_QUIT_RANDOM_MATCH => '&bRandom match\n&aClick to join',
            LangConstants::MINIGAME_FORMS_QUIT_MODE_MATCH => '%0 Match\n&aClick to join',
            LangConstants::MINIGAME_FORMS_QUIT_RANDOM_MODE_MATCH => '&bRandom %0 Match\n&aClick to join',

            LangConstants::MINIGAME_FORMS_TELEPORTER_TITLE => 'Spectator Menu',
            LangConstants::MINIGAME_FORMS_TELEPORTER_SELECT => 'Select player: ',
            LangConstants::MINIGAME_FORMS_TELEPORTER_TP_TO => 'Teleport to %0',
            LangConstants::MINIGAME_TELEPORTER_GAME_NOT_PLAYER => '&cThat player is not in the game anymore!',
            LangConstants::MINIGAME_TELEPORTER_GAME_NOT_RUNNING => '&cThe game is not running!',
            LangConstants::MINIGAME_TELEPORTER_GAME_NOT_YOU => '&cYou are not in the game anymore!',

            LangConstants::MINIGAME_FORMS_TEAMS_TITLE => 'Teams Selector',
            LangConstants::MINIGAME_FORMS_TEAMS_CONTENT => 'Select a team:',
            LangConstants::MINIGAME_TEAMS_SELECT_SAME => '&cYou can\'t choose the same team!',
            LangConstants::MINIGAME_TEAMS_SELECT_FULL => '&cThis team is full',
            LangConstants::MINIGAME_TEAMS_SELECT_STARTING => '&cYou cannot change teams now - the game is starting',
            LangConstants::MINIGAME_TEAMS_SELECT_JOINED => '&eYou have joined the %0 &eteam',
            LangConstants::MINIGAME_TEAMS_PERM => '&cYou don\'t have permission to choose a team. Buy the &l&aEMERALD &r&cor &l&bLEGEND &r&crank at &bngmc.co/store &cto choose one!',

            LangConstants::MINIGAME_FORMS_MAP_TITLE => 'Map Selector',
            LangConstants::MINIGAME_FORMS_MAP_CONTENT => 'Choose the map you want to play: ',
            LangConstants::MINIGAME_MAP_VOTED => '&aYou voted for &6%0',
            LangConstants::MINIGAME_MAP_RUNNING => '&cYou cannot vote for the map now - the game is starting'
        ];
    }

    public function getLocale(): string
    {
        return 'en_au';
    }

    public function getName(): string
    {
        return 'English';
    }

    public function getFlag(): string
    {
        return 'https://cdn.nethergames.org/img/flags/australia.png';
    }

    public function getCredits(): string
    {
        return 'NetherGames';
    }
}